server:
  port: 8082

spring:
  application:
    name: notification-service
  config:
    import: optional:configserver:http://localhost:8888
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: notification-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.value.default.type: org.hwmoodle.core.dto.UserNotificationEvent
        spring.json.trusted.packages: org.hwmoodle.core.dto
  mail:
    host: ${SPRING_MAIL_HOST:smtp.example.com}
    port: ${SPRING_MAIL_PORT:465}
    username: ${SPRING_MAIL_USERNAME:}
    password: ${SPRING_MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: false
          ssl:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://notification-db:5432/notification_db}
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME:}
    password: ${SPRING_DATASOURCE_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

app:
  notification:
    sender-email: ${APP_NOTIFICATION_SENDER_EMAIL:}
    topic: user-events

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,circuitbreakers
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true

resilience4j:
  circuitbreaker:
    instances:
      emailServiceCB:
        register-health-indicator: true
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10000
        permitted-number-of-calls-in-half-open-state: 3
        slow-call-rate-threshold: 100
        slow-call-duration-threshold: 2000
  timelimiter:
    instances:
      emailServiceCB:
        cancel-running-future: true
        timeout-duration: 5000

